find_program(GLSLC NAMES glslc glslc.exe)

if(NOT GLSLC)
    message(WARNING "glslc not found. Shaders must be manually compiled")
else()
    file(COPY ${SHADER_DIR} DESTINATION ${OUT_DIR}/../)
    file(GLOB_RECURSE SHADER_SRC "${OUT_DIR}/*.vert" "${OUT_DIR}/*.frag")
    foreach(file ${SHADER_SRC})
        message(STATUS "Compiling Shader Source: ${file}")
        execute_process(COMMAND ${GLSLC} ${file} -o ${file}.spv RESULT_VARIABLE GLSLC_CMD_RES OUTPUT_VARIABLE GLSLC_CMD_OUT)
        message(STATUS "\tGLSLC: ${GLSLC} ${file} -o ${file}.spv")
        file(REMOVE ${file})
    endforeach()
    file(REMOVE ${OUT_DIR}/CompileShaders.cmake)
endif()